name: Test

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: write file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ env.home}}/CHANGELOG.md
          contents: ${{ steps.get_data.outputs.changelog }}
          write-mode: overwrite
