name: Test

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: changelog
        id: changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |	
          echo ${{ steps.changelog.outputs.changelog }}
